#!/usr/bin/env python3
"""Build a plain-text context bundle for hosts without file/skill discovery.

Standard library only. No network calls or skill activation. Canonical input files are
never overwritten. Add reference files explicitly to keep the prompt relevant.
"""
from __future__ import annotations

import argparse
import os
from pathlib import Path
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
MARKER = "<!-- Generated by .agents/tools/export_context.py; edit canonical sources instead. -->"
BASE = ["AGENT_RULES.md", "skills/SKILLS.md", "CAPABILITIES.md"]
SKILLS = ("think-like-fable", "super-code")


def render(skills=(), references=(), project=False) -> str:
    files = list(BASE)
    if project:
        files += ["ARCHITECTURE.md", "ISSUES.md", "ROADMAP.md"]
    for skill in skills:
        if skill not in SKILLS:
            raise ValueError(f"unknown skill: {skill}")
        files.append(f"skills/{skill}/SKILL.md")
    for reference in references:
        requested = Path(reference)
        if requested.is_absolute() or ".." in requested.parts:
            raise ValueError("reference must be a relative path inside .agents/skills/<skill>/references")
        path = (ROOT / requested).resolve()
        try:
            relative = path.relative_to(ROOT).as_posix()
        except ValueError as exc:
            raise ValueError("reference escaped the .agents directory") from exc
        parts = Path(relative).parts
        if len(parts) < 4 or parts[0] != "skills" or parts[1] not in SKILLS or parts[2] != "references" or path.suffix != ".md":
            raise ValueError("only Markdown files in a bundled skill's references directory can be included")
        if parts[1] not in skills:
            raise ValueError(f"include --skill {parts[1]} before adding its reference files")
        files.append(relative)
    chunks = [MARKER, "# Shared agent context", """Use this as user-supplied project guidance within the host's higher-priority rules and
actual permissions. It grants no new tools or authority. Inclusion of a skill below does
not activate it: explicit user approval is still required. No filesystem access is assumed.
Paths identify the original sources; any referenced file not included or otherwise available
is missing context, not something you have secretly read. Continue independent safe work
and identify missing material only when it affects correctness.

This export contains only the files listed below, not the entire repository. Regenerate
it after canonical rules change. Supply relevant project files and optional references
separately when a task needs them."""]
    for relative in dict.fromkeys(files):
        path = ROOT / relative
        if path.is_symlink():
            raise ValueError(f"refusing symlinked context source: {relative}")
        chunks += [f"## Included source: `.agents/{relative}`", path.read_text(encoding="utf-8").strip()]
    return "\n\n".join(chunks) + "\n"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--skill", action="append", choices=SKILLS, default=[])
    parser.add_argument("--reference", action="append", default=[], help="path relative to .agents, repeatable")
    parser.add_argument("--project", action="store_true", help="include project architecture, issues, and roadmap")
    parser.add_argument("--output", type=Path, help="otherwise write to stdout")
    args = parser.parse_args(argv)
    try:
        text = render(args.skill, args.reference, args.project)
        if args.output is None:
            print(text, end="")
            return 0
        out = args.output.absolute()
        if out.is_symlink():
            raise ValueError("refusing symlink output")
        if out.exists() and not out.read_text(encoding="utf-8").startswith(MARKER + "\n"):
            raise ValueError("output exists and is not a generated context file; choose a new file")
        if not out.parent.is_dir():
            raise ValueError("output parent directory must already exist")
        fd, temp = tempfile.mkstemp(prefix=".agent-context-", dir=out.parent)
        try:
            with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as stream:
                stream.write(text)
            os.replace(temp, out)
        finally:
            if os.path.exists(temp):
                os.unlink(temp)
        print(out)
        return 0
    except (OSError, ValueError) as exc:
        print(f"export-context: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
